import React from 'react';
import { useState, useRef } from 'react';
import { View, Text, Pressable, StyleSheet, Dimensions, FlatList } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { LinearGradient } from 'expo-linear-gradient';

import { useColorScheme } from '@/hooks/use-color-scheme';

const { width } = Dimensions.get('window');

const ONBOARDING_STEPS = [
  {
    id: '1',
    icon: 'sparkles',
    title: 'AI-Powered Workouts',
    description: 'Get personalized workout plans generated by AI based on your goals, fitness level, and available equipment.',
  },
  {
    id: '2',
    icon: 'barbell-outline',
    title: 'Track Your Progress',
    description: 'Log your workouts, track personal records, and visualize your fitness journey with detailed analytics.',
  },
  {
    id: '3',
    icon: 'fitness-outline',
    title: 'Exercise Library',
    description: 'Access hundreds of exercises with proper form guides, muscle group targeting, and difficulty ratings.',
  },
  {
    id: '4',
    icon: 'trophy-outline',
    title: 'Achieve Your Goals',
    description: 'Set fitness goals, maintain streaks, and celebrate achievements as you progress on your fitness journey.',
  },
];

export default function OnboardingScreen() {
  const colorScheme = useColorScheme();
  const isDark = colorScheme === 'dark';
  const router = useRouter();
  const [currentIndex, setCurrentIndex] = useState(0);
  const flatListRef = useRef<FlatList>(null);

  const handleNext = () => {
    if (currentIndex < ONBOARDING_STEPS.length - 1) {
      flatListRef.current?.scrollToIndex({ index: currentIndex + 1, animated: true });
      setCurrentIndex(currentIndex + 1);
    } else {
      router.replace('/(tabs)');
    }
  };

  const handleSkip = () => {
    router.replace('/(tabs)');
  };

  const renderItem = ({ item }: { item: typeof ONBOARDING_STEPS[0] }) => (
    <View style={styles.slide}>
      <View style={styles.iconContainer}>
        <LinearGradient colors={['#3b82f6', '#8b5cf6']} style={styles.iconGradient}>
          <Ionicons name={item.icon as any} size={64} color="white" />
        </LinearGradient>
      </View>
      <Text style={[styles.title, isDark && styles.textWhite]}>{item.title}</Text>
      <Text style={[styles.description, isDark && styles.textLight]}>{item.description}</Text>
    </View>
  );

  const onViewableItemsChanged = useRef(({ viewableItems }: any) => {
    if (viewableItems.length > 0) {
      setCurrentIndex(viewableItems[0].index);
    }
  }).current;

  return (
    <SafeAreaView style={[styles.container, isDark && styles.containerDark]}>
      <View style={styles.header}>
        <Pressable onPress={handleSkip}>
          <Text style={[styles.skipText, isDark && styles.textLight]}>Skip</Text>
        </Pressable>
      </View>

      <FlatList
        ref={flatListRef}
        data={ONBOARDING_STEPS}
        renderItem={renderItem}
        keyExtractor={(item) => item.id}
        horizontal
        pagingEnabled
        showsHorizontalScrollIndicator={false}
        onViewableItemsChanged={onViewableItemsChanged}
        viewabilityConfig={{ viewAreaCoveragePercentThreshold: 50 }}
        style={styles.flatList}
      />

      <View style={styles.footer}>
        <View style={styles.pagination}>
          {ONBOARDING_STEPS.map((_, index) => (
            <View
              key={index}
              style={[
                styles.dot,
                index === currentIndex && styles.dotActive,
                isDark && index !== currentIndex && styles.dotDark,
              ]}
            />
          ))}
        </View>

        <Pressable style={styles.nextButton} onPress={handleNext}>
          <LinearGradient colors={['#3b82f6', '#8b5cf6']} style={styles.nextButtonGradient}>
            <Text style={styles.nextButtonText}>
              {currentIndex === ONBOARDING_STEPS.length - 1 ? 'Get Started' : 'Next'}
            </Text>
            <Ionicons name="arrow-forward" size={20} color="white" />
          </LinearGradient>
        </Pressable>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8fafc' },
  containerDark: { backgroundColor: '#0f172a' },
  header: { flexDirection: 'row', justifyContent: 'flex-end', paddingHorizontal: 24, paddingVertical: 16 },
  skipText: { fontSize: 16, color: '#64748b' },
  flatList: { flex: 1 },
  slide: { width, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 40 },
  iconContainer: { marginBottom: 48 },
  iconGradient: {
    width: 140,
    height: 140,
    borderRadius: 70,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: { fontSize: 28, fontWeight: 'bold', color: '#0f172a', textAlign: 'center', marginBottom: 16 },
  description: { fontSize: 16, color: '#64748b', textAlign: 'center', lineHeight: 24 },
  footer: { paddingHorizontal: 24, paddingBottom: 24 },
  pagination: { flexDirection: 'row', justifyContent: 'center', marginBottom: 32 },
  dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#cbd5e1', marginHorizontal: 4 },
  dotActive: { width: 24, backgroundColor: '#3b82f6' },
  dotDark: { backgroundColor: '#334155' },
  nextButton: { borderRadius: 12, overflow: 'hidden' },
  nextButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    gap: 8,
  },
  nextButtonText: { fontSize: 18, fontWeight: '600', color: 'white' },
  textWhite: { color: 'white' },
  textLight: { color: '#94a3b8' },
});
