import { useState, useRef } from 'react';
import { View, Text, Pressable, StyleSheet, Dimensions, FlatList } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';

import { useTheme } from '../../../providers/theme-provider';
import { useAuthStore } from '../../../stores/auth-store';

const { width } = Dimensions.get('window');

const ONBOARDING_STEPS = [
  {
    id: '1',
    icon: 'sparkles',
    title: 'AI-Powered Workouts',
    description: 'Get personalized workout plans generated by AI based on your goals, fitness level, and available equipment.',
  },
  {
    id: '2',
    icon: 'barbell-outline',
    title: 'Track Your Progress',
    description: 'Log your workouts, track personal records, and visualize your fitness journey with detailed analytics.',
  },
  {
    id: '3',
    icon: 'fitness-outline',
    title: 'Exercise Library',
    description: 'Access hundreds of exercises with proper form guides, muscle group targeting, and difficulty ratings.',
  },
  {
    id: '4',
    icon: 'trophy-outline',
    title: 'Achieve Your Goals',
    description: 'Set fitness goals, maintain streaks, and celebrate achievements as you progress on your fitness journey.',
  },
];

export default function OnboardingScreen() {
  const { colors } = useTheme();
  const { completeOnboarding } = useAuthStore();
  const [currentIndex, setCurrentIndex] = useState(0);
  const flatListRef = useRef<FlatList>(null);

  const handleNext = async () => {
    if (currentIndex < ONBOARDING_STEPS.length - 1) {
      flatListRef.current?.scrollToIndex({ index: currentIndex + 1, animated: true });
      setCurrentIndex(currentIndex + 1);
    } else {
      await completeOnboarding({});
    }
  };

  const handleSkip = async () => {
    await completeOnboarding({});
  };

  const renderItem = ({ item }: { item: typeof ONBOARDING_STEPS[0] }) => (
    <View style={styles.slide}>
      <View style={styles.iconContainer}>
        <LinearGradient
          colors={colors.gradient.primary as unknown as [string, string]}
          style={styles.iconGradient}
        >
          <Ionicons name={item.icon as any} size={64} color={colors.text.onPrimary} />
        </LinearGradient>
      </View>
      <Text style={[styles.title, { color: colors.text.primary }]}>{item.title}</Text>
      <Text style={[styles.description, { color: colors.text.secondary }]}>{item.description}</Text>
    </View>
  );

  const onViewableItemsChanged = useRef(({ viewableItems }: any) => {
    if (viewableItems.length > 0) {
      setCurrentIndex(viewableItems[0].index);
    }
  }).current;

  return (
    <SafeAreaView style={[styles.container, { backgroundColor: colors.background.base }]}>
      <View style={styles.header}>
        <Pressable onPress={handleSkip}>
          <Text style={[styles.skipText, { color: colors.text.secondary }]}>Skip</Text>
        </Pressable>
      </View>

      <FlatList
        ref={flatListRef}
        data={ONBOARDING_STEPS}
        renderItem={renderItem}
        keyExtractor={(item) => item.id}
        horizontal
        pagingEnabled
        showsHorizontalScrollIndicator={false}
        onViewableItemsChanged={onViewableItemsChanged}
        viewabilityConfig={{ viewAreaCoveragePercentThreshold: 50 }}
        style={styles.flatList}
      />

      <View style={styles.footer}>
        <View style={styles.pagination}>
          {ONBOARDING_STEPS.map((_, index) => (
            <View
              key={index}
              style={[
                styles.dot,
                { backgroundColor: colors.border.default },
                index === currentIndex && [styles.dotActive, { backgroundColor: colors.primary.base }],
              ]}
            />
          ))}
        </View>

        <Pressable style={styles.nextButton} onPress={handleNext}>
          <LinearGradient
            colors={colors.gradient.primary as unknown as [string, string]}
            style={styles.nextButtonGradient}
          >
            <Text style={[styles.nextButtonText, { color: colors.text.onPrimary }]}>
              {currentIndex === ONBOARDING_STEPS.length - 1 ? 'Get Started' : 'Next'}
            </Text>
            <Ionicons name="arrow-forward" size={20} color={colors.text.onPrimary} />
          </LinearGradient>
        </Pressable>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  header: { flexDirection: 'row', justifyContent: 'flex-end', paddingHorizontal: 24, paddingVertical: 16 },
  skipText: { fontSize: 16 },
  flatList: { flex: 1 },
  slide: { width, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 40 },
  iconContainer: { marginBottom: 48 },
  iconGradient: {
    width: 140,
    height: 140,
    borderRadius: 70,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: { fontSize: 28, fontWeight: 'bold', textAlign: 'center', marginBottom: 16 },
  description: { fontSize: 16, textAlign: 'center', lineHeight: 24 },
  footer: { paddingHorizontal: 24, paddingBottom: 24 },
  pagination: { flexDirection: 'row', justifyContent: 'center', marginBottom: 32 },
  dot: { width: 8, height: 8, borderRadius: 4, marginHorizontal: 4 },
  dotActive: { width: 24 },
  nextButton: { borderRadius: 12, overflow: 'hidden' },
  nextButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    gap: 8,
  },
  nextButtonText: { fontSize: 18, fontWeight: '600' },
});
